// client/src/app/components/graph/graph.component.ts
import { Component, ElementRef, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { CommonModule } from '@angular/common';
import * as d3 from 'd3';
import { Subscription, combineLatest } from 'rxjs';
import { PersonaService } from '../../services/persona.service';
import { MatchService } from '../../services/match.service';
import { Persona } from '../../models/persona.model';
import { Match } from '../../models/match.model';
import { IconComponent } from '../../shared/icon.component';
import { ReportPanelComponent } from '../report-panel/report-panel.component';
import { hueOf, initialOf } from '../../shared/persona-helpers';

interface SimNode extends d3.SimulationNodeDatum {
  id: string;
  name: string;
  hue: number;
  initial: string;
}
interface SimEdge extends d3.SimulationLinkDatum<SimNode> {
  matchId: string;
  weight: number;
}

@Component({
  selector: 'app-graph',
  standalone: true,
  imports: [CommonModule, IconComponent, ReportPanelComponent],
  templateUrl: './graph.component.html',
})
export class GraphComponent implements OnInit, OnDestroy {
  @ViewChild('svgRoot', { static: true }) svgRoot!: ElementRef<SVGSVGElement>;

  private subs: Subscription[] = [];
  private personas: Persona[] = [];
  private matches: Match[] = [];

  focused: SimNode | null = null;
  focusedMatches: Array<{ match: Match; other: SimNode }> = [];
  drawerMatch: Match | null = null;
  drawerA: Persona | null = null;
  drawerB: Persona | null = null;

  nodeCount = 0;
  edgeCount = 0;
  strongCount = 0;

  constructor(
    private personaService: PersonaService,
    private matchService: MatchService,
  ) {}

  ngOnInit(): void {
    this.personaService.load().subscribe();
    this.matchService.load().subscribe();
    this.subs.push(
      combineLatest([this.personaService.personas$, this.matchService.matches$]).subscribe(([p, m]) => {
        this.personas = p;
        this.matches = m;
        this.nodeCount = p.length;
        this.edgeCount = m.length;
        this.strongCount = m.filter(x => x.score >= 80).length;
        this.render();
      }),
    );
  }

  ngOnDestroy(): void { this.subs.forEach(s => s.unsubscribe()); }

  private render(): void {
    const svg = d3.select(this.svgRoot.nativeElement);
    svg.selectAll('*').remove();
    if (!this.matches.length) return;

    const width = 1000, height = 720;
    svg.attr('viewBox', `0 0 ${width} ${height}`).attr('preserveAspectRatio', 'xMidYMid meet');

    // build nodes from everyone referenced by matches
    const nodeMap = new Map<string, SimNode>();
    for (const m of this.matches) {
      for (const side of ['personaAId', 'personaBId'] as const) {
        const v = m[side];
        if (typeof v === 'string') continue;
        if (!v._id) continue;
        if (!nodeMap.has(v._id)) {
          nodeMap.set(v._id, {
            id: v._id,
            name: v.name,
            hue: hueOf(v),
            initial: initialOf(v),
          });
        }
      }
    }
    const nodes = Array.from(nodeMap.values());
    const ownIds = new Set(this.personas.map(p => p._id).filter(Boolean) as string[]);

    const edges: SimEdge[] = this.matches.map(m => ({
      source: (typeof m.personaAId === 'string' ? m.personaAId : m.personaAId._id!),
      target: (typeof m.personaBId === 'string' ? m.personaBId : m.personaBId._id!),
      matchId: m._id,
      weight: m.score,
    }));

    // defs
    const defs = svg.append('defs');
    const grad = defs.append('radialGradient').attr('id', 'bgglow').attr('cx', '50%').attr('cy', '50%');
    grad.append('stop').attr('offset', '0%').attr('stop-color', 'var(--accent)').attr('stop-opacity', '0.12');
    grad.append('stop').attr('offset', '100%').attr('stop-color', 'var(--accent)').attr('stop-opacity', '0');

    // background glow + concentric rings
    svg.append('circle').attr('cx', width / 2).attr('cy', height / 2).attr('r', 300).attr('fill', 'url(#bgglow)');
    for (const r of [120, 200, 280]) {
      svg.append('circle')
        .attr('cx', width / 2).attr('cy', height / 2).attr('r', r)
        .attr('fill', 'none').attr('stroke', 'var(--border)')
        .attr('stroke-dasharray', '2 6').attr('opacity', 0.6);
    }

    const sim = d3.forceSimulation<SimNode>(nodes)
      .force('link', d3.forceLink<SimNode, SimEdge>(edges).id(d => d.id).distance(e => 220 - (e.weight / 100) * 120))
      .force('charge', d3.forceManyBody().strength(-260))
      .force('center', d3.forceCenter(width / 2, height / 2))
      .force('collide', d3.forceCollide(36));

    const linkGroup = svg.append('g');
    const link = linkGroup.selectAll('line')
      .data(edges)
      .enter()
      .append('line')
      .attr('stroke', 'var(--accent)')
      .attr('stroke-opacity', d => 0.2 + (d.weight / 100) * 0.5)
      .attr('stroke-width', d => 0.5 + (d.weight / 100) * 3)
      .style('cursor', 'pointer')
      .on('click', (_, e) => this.openEdgeReport(e));

    const nodeGroup = svg.append('g');
    const node = nodeGroup.selectAll('g.gn')
      .data(nodes)
      .enter()
      .append('g')
      .attr('class', 'graph-node gn')
      .style('cursor', 'pointer')
      .on('click', (_, n) => this.focusNode(n, nodes, edges));

    node.append('circle')
      .attr('r', d => ownIds.has(d.id) ? 28 : 20)
      .attr('fill', d => `hsl(${d.hue} 80% 62%)`)
      .attr('stroke', d => ownIds.has(d.id) ? `hsl(${d.hue} 90% 80%)` : 'var(--accent-2)')
      .attr('stroke-width', 1.5);

    node.append('text')
      .attr('text-anchor', 'middle')
      .attr('dy', 4)
      .attr('font-family', 'Fraunces, serif')
      .attr('font-weight', 500)
      .attr('font-size', d => ownIds.has(d.id) ? 18 : 13)
      .attr('fill', 'white')
      .text(d => d.initial);

    node.append('title').text(d => d.name);

    sim.on('tick', () => {
      link
        .attr('x1', d => (d.source as SimNode).x!)
        .attr('y1', d => (d.source as SimNode).y!)
        .attr('x2', d => (d.target as SimNode).x!)
        .attr('y2', d => (d.target as SimNode).y!);
      node.attr('transform', d => `translate(${d.x}, ${d.y})`);
    });
  }

  private openEdgeReport(edge: SimEdge): void {
    const m = this.matches.find(x => x._id === edge.matchId);
    if (!m) return;
    this.drawerMatch = m;
    this.drawerA = typeof m.personaAId === 'string' ? null : m.personaAId;
    this.drawerB = typeof m.personaBId === 'string' ? null : m.personaBId;
  }

  closeDrawer(): void { this.drawerMatch = null; }

  private focusNode(n: SimNode, nodes: SimNode[], edges: SimEdge[]): void {
    if (this.focused?.id === n.id) { this.focused = null; this.focusedMatches = []; return; }
    this.focused = n;
    this.focusedMatches = edges
      .filter(e => (e.source as SimNode).id === n.id || (e.target as SimNode).id === n.id)
      .sort((a, b) => b.weight - a.weight)
      .map(e => {
        const otherId = (e.source as SimNode).id === n.id ? (e.target as SimNode).id : (e.source as SimNode).id;
        const other = nodes.find(x => x.id === otherId)!;
        const match = this.matches.find(x => x._id === e.matchId)!;
        return { match, other };
      });
  }

  clearFocus(): void { this.focused = null; this.focusedMatches = []; }

  openFocusMatch(match: Match): void { this.openEdgeReport({ matchId: match._id } as SimEdge); }
}

<div class="page">
  <div class="row between" style="margin-bottom:20px; align-items:flex-end">
    <div>
      <h1>Network</h1>
      <div class="sub">A visual map of every self on the platform. Thicker lines = stronger matches. Click a node to focus; click a line to read its AI compatibility report.</div>
    </div>
  </div>

  <div class="graph-shell">
    <div class="graph-panel">
      <h5>Legend</h5>
      <div class="graph-legend">
        <div><span class="dot-u"></span> Your personas</div>
        <div><span class="dot-o"></span> Others</div>
        <div class="muted" style="margin-top:12px; font-size:11px">
          Edge thickness = compatibility score. Click a node to isolate its connections. Click an edge to open the AI report.
        </div>
      </div>
      <div class="divider"></div>
      <h5>Stats</h5>
      <div class="graph-legend">
        <div>{{ nodeCount }} nodes · {{ edgeCount }} edges</div>
        <div>{{ strongCount }} strong (≥80) links</div>
      </div>
    </div>

    <div class="graph-canvas-wrap">
      <svg #svgRoot></svg>
    </div>

    <div class="graph-panel">
      <h5>Focus</h5>
      <ng-container *ngIf="focused; else noFocus">
        <div style="font-size:14px; font-weight:600; margin-bottom:8px">{{ focused.name }}</div>
        <div class="muted" style="font-size:12px; margin-bottom:12px">Connected matches:</div>
        <div style="display:flex; flex-direction:column; gap:6px">
          <div *ngFor="let item of focusedMatches"
               (click)="openFocusMatch(item.match)"
               style="padding:10px 12px; background:var(--card-2); border-radius:8px; border:1px solid var(--border); cursor:pointer; display:flex; justify-content:space-between; align-items:center">
            <span style="font-size:12.5px">{{ item.other.name }}</span>
            <b style="font-family:'Fraunces', serif; font-size:14px; color:var(--accent)">{{ item.match.score }}%</b>
          </div>
        </div>
        <button class="btn btn-ghost btn-sm" style="width:100%; margin-top:14px" type="button" (click)="clearFocus()">
          Clear focus
        </button>
      </ng-container>
      <ng-template #noFocus>
        <div class="muted" style="font-size:12.5px; line-height:1.55">
          Click any node to isolate its connections. Click an edge to open its AI compatibility report.
        </div>
      </ng-template>
    </div>
  </div>
</div>

<app-report-panel
  [match]="drawerMatch"
  [a]="drawerA"
  [b]="drawerB"
  (close)="closeDrawer()">
</app-report-panel>

// prototype/src/graph.jsx
const { useState: gS, useEffect: gE, useRef: gR, useMemo: gM } = React;

function GraphPage({ personas, others, matches, openMatch, pulse }) {
  const [hoverNode, setHoverNode] = gS(null);
  const [activeNode, setActiveNode] = gS(null);
  const [tip, setTip] = gS(null);

  // Build nodes + layout with a simple radial force simulation (deterministic)
  const { nodes, links } = gM(() => {
    const userNodes = personas.map((p,i) => ({
      id: p.id, kind:'user', label: p.name, initial: p.initial, hue: p.hue,
      r: 26 + (p.scoreAvg/10),
    }));
    const otherNodes = others.map((o,i) => ({
      id: o.id, kind:'other', label: o.name, initial: o.initial, hue: o.hue,
      r: 18,
    }));
    const all = [...userNodes, ...otherNodes];
    // initial positions: users on inner ring, others on outer
    userNodes.forEach((n,i) => {
      const a = (i / userNodes.length) * Math.PI * 2;
      n.x = 500 + Math.cos(a) * 140;
      n.y = 360 + Math.sin(a) * 140;
    });
    otherNodes.forEach((n,i) => {
      const a = (i / otherNodes.length) * Math.PI * 2 + 0.3;
      n.x = 500 + Math.cos(a) * 290;
      n.y = 360 + Math.sin(a) * 220;
    });
    const links = matches.map(m => ({ ...m, source: m.a, target: m.b, weight: m.score/100 }));
    // simple relax: pull linked nodes toward each other
    for (let it=0; it<60; it++) {
      links.forEach(l => {
        const a = all.find(n=>n.id===l.source), b = all.find(n=>n.id===l.target);
        const dx = b.x-a.x, dy = b.y-a.y;
        const d = Math.sqrt(dx*dx+dy*dy) || 1;
        const target = 180 - l.weight*80;
        const f = (d - target) * 0.04;
        const ux = dx/d, uy = dy/d;
        if (a.kind !== 'user') { a.x += ux*f; a.y += uy*f; }
        if (b.kind !== 'user') { b.x -= ux*f; b.y -= uy*f; }
      });
      // repel
      for (let i=0; i<all.length; i++) for (let j=i+1; j<all.length; j++) {
        const a=all[i], b=all[j];
        const dx=b.x-a.x, dy=b.y-a.y;
        const d=Math.sqrt(dx*dx+dy*dy)||1;
        if (d<80) {
          const f=(80-d)*0.08; const ux=dx/d, uy=dy/d;
          if (a.kind!=='user') { a.x -= ux*f; a.y -= uy*f; }
          if (b.kind!=='user') { b.x += ux*f; b.y += uy*f; }
        }
      }
    }
    return { nodes: all, links };
  }, [personas, others, matches]);

  const isConnected = (nodeId, linkId) => {
    const l = links.find(x => x.id === linkId);
    return l && (l.source === nodeId || l.target === nodeId);
  };
  const isNodeLinkedToActive = (id) => {
    if (!activeNode) return true;
    if (id === activeNode) return true;
    return links.some(l => (l.source===activeNode && l.target===id) || (l.target===activeNode && l.source===id));
  };

  return (
    <div className="page">
      <div className="row between" style={{marginBottom:20, alignItems:'flex-end'}}>
        <div>
          <h1>Compatibility graph</h1>
          <div className="sub">Your personas, their matches, and the tissue of connection between them.</div>
        </div>
        <div className="row" style={{gap:8}}>
          <button className="btn btn-ghost"><Ic.filter/> Filter</button>
          <button className="btn btn-ghost"><Ic.refresh/> Rebuild</button>
        </div>
      </div>

      <div className="graph-shell">
        <div className="graph-panel">
          <h5>Legend</h5>
          <div className="graph-legend">
            <div><span className="dot-u"/> Your personas</div>
            <div><span className="dot-o"/> Others</div>
            <div className="muted" style={{marginTop:12, fontSize:11}}>Edge thickness = compatibility score. Hover a node for details, click to isolate.</div>
          </div>
          <div className="divider"/>
          <h5>Stats</h5>
          <div className="graph-legend">
            <div>{personas.length} of yours · {others.length} others</div>
            <div>{links.length} active edges</div>
            <div>{links.filter(l=>l.score>=90).length} strong links</div>
          </div>
        </div>

        <div className="graph-canvas-wrap" onMouseLeave={()=>setTip(null)}>
          <svg viewBox="0 0 1000 720" preserveAspectRatio="xMidYMid meet">
            <defs>
              <radialGradient id="bgglow" cx="50%" cy="50%">
                <stop offset="0%" stopColor="var(--accent)" stopOpacity="0.12"/>
                <stop offset="100%" stopColor="var(--accent)" stopOpacity="0"/>
              </radialGradient>
              <filter id="glow">
                <feGaussianBlur stdDeviation="4" result="b"/>
                <feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge>
              </filter>
            </defs>
            <circle cx="500" cy="360" r="300" fill="url(#bgglow)"/>
            {/* rings */}
            {[120, 200, 280].map((r,i) => (
              <circle key={i} cx="500" cy="360" r={r} fill="none" stroke="var(--border)" strokeDasharray="2 6" opacity="0.6"/>
            ))}
            {/* edges */}
            {links.map(l => {
              const a = nodes.find(n=>n.id===l.source), b = nodes.find(n=>n.id===l.target);
              const active = activeNode && (l.source===activeNode || l.target===activeNode);
              const dim = activeNode && !active;
              const width = 0.5 + l.weight * 3;
              return (
                <g key={l.id} onClick={()=>openMatch(l.id)} style={{cursor:'pointer'}}>
                  <line x1={a.x} y1={a.y} x2={b.x} y2={b.y}
                    stroke={active ? 'var(--accent)' : 'var(--accent)'}
                    strokeOpacity={dim ? 0.08 : (0.2 + l.weight*0.5)}
                    strokeWidth={width}/>
                  {pulse && !dim && (
                    <circle r="3" fill="var(--accent-2)">
                      <animateMotion dur={`${2.5 + (l.score%5)*0.3}s`} repeatCount="indefinite"
                        path={`M${a.x} ${a.y} L ${b.x} ${b.y}`}/>
                      <animate attributeName="opacity" values="0;1;0" dur={`${2.5 + (l.score%5)*0.3}s`} repeatCount="indefinite"/>
                    </circle>
                  )}
                </g>
              );
            })}
            {/* nodes */}
            {nodes.map(n => {
              const dim = activeNode && !isNodeLinkedToActive(n.id);
              const highlighted = hoverNode === n.id || activeNode === n.id;
              return (
                <g key={n.id} className="graph-node" opacity={dim ? 0.25 : 1}
                   onMouseEnter={(e)=>{ setHoverNode(n.id); setTip({ x: n.x, y: n.y, node: n }); }}
                   onMouseLeave={()=>{ setHoverNode(null); setTip(null); }}
                   onClick={()=>setActiveNode(a => a===n.id ? null : n.id)}>
                  {n.kind==='user' && (
                    <circle cx={n.x} cy={n.y} r={n.r+10} fill={`hsl(${n.hue} 80% 65%)`} opacity={highlighted ? 0.35 : 0.18} filter="url(#glow)">
                      {pulse && <animate attributeName="r" values={`${n.r+8};${n.r+14};${n.r+8}`} dur="3s" repeatCount="indefinite"/>}
                    </circle>
                  )}
                  <circle cx={n.x} cy={n.y} r={n.r}
                    fill={n.kind==='user' ? `hsl(${n.hue} 80% 62%)` : 'var(--card-2)'}
                    stroke={n.kind==='user' ? `hsl(${n.hue} 90% 80%)` : 'var(--accent-2)'}
                    strokeWidth={highlighted ? 3 : 1.5}/>
                  <text x={n.x} y={n.y+4} textAnchor="middle" fontFamily="Fraunces, serif" fontWeight="500"
                        fontSize={n.kind==='user' ? 18 : 13}
                        fill={n.kind==='user' ? 'white' : 'var(--text)'}>
                    {n.initial}
                  </text>
                  {highlighted && (
                    <text x={n.x} y={n.y + n.r + 16} textAnchor="middle" fontSize="11" fill="var(--text-dim)">
                      {n.label}
                    </text>
                  )}
                </g>
              );
            })}
          </svg>

          {tip && (
            <div className="graph-tooltip" style={{ left: `${(tip.x/1000)*100}%`, top: `${(tip.y/720)*100}%`, transform: 'translate(-50%, -130%)' }}>
              <b>{tip.node.label}</b>
              <small>{tip.node.kind==='user' ? 'Your persona' : 'External node'}</small>
              <small style={{marginTop:4}}>
                {links.filter(l=>l.source===tip.node.id || l.target===tip.node.id).length} connections
              </small>
            </div>
          )}
        </div>

        <div className="graph-panel">
          <h5>Focus</h5>
          {activeNode ? (
            <>
              <div style={{fontSize:14, fontWeight:600, marginBottom:8}}>
                {nodes.find(n=>n.id===activeNode).label}
              </div>
              <div className="muted" style={{fontSize:12, marginBottom:12}}>Connected matches:</div>
              <div style={{display:'flex', flexDirection:'column', gap:6}}>
                {links.filter(l=>l.source===activeNode || l.target===activeNode).sort((a,b)=>b.score-a.score).map(l => {
                  const other = nodes.find(n => n.id === (l.source===activeNode ? l.target : l.source));
                  return (
                    <div key={l.id} onClick={()=>openMatch(l.id)} style={{
                      padding:'10px 12px', background:'var(--card-2)', borderRadius:8,
                      border:'1px solid var(--border)', cursor:'pointer',
                      display:'flex', justifyContent:'space-between', alignItems:'center'
                    }}>
                      <span style={{fontSize:12.5}}>{other.label}</span>
                      <b style={{fontFamily:'Fraunces, serif', fontSize:14, color:'var(--accent)'}}>{l.score}%</b>
                    </div>
                  );
                })}
              </div>
              <button className="btn btn-ghost btn-sm" style={{width:'100%', marginTop:14}} onClick={()=>setActiveNode(null)}>Clear focus</button>
            </>
          ) : (
            <div className="muted" style={{fontSize:12.5, lineHeight:1.55}}>
              Click any node to isolate its connections. Click an edge to open its AI compatibility report.
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { GraphPage });
