// client/src/app/components/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterLink } from '@angular/router';
import { map, Observable } from 'rxjs';
import { PersonaService } from '../../services/persona.service';
import { MatchService } from '../../services/match.service';
import { AuthService } from '../../services/auth.service';
import { Persona } from '../../models/persona.model';
import { Match } from '../../models/match.model';
import { IconComponent } from '../../shared/icon.component';
import { PersonaOrbComponent } from '../../shared/persona-orb.component';
import { initialOf, hueOf, ownerNameOf, ownerPossessive } from '../../shared/persona-helpers';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterLink, IconComponent, PersonaOrbComponent],
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent implements OnInit {
  personas$ = this.personaService.personas$;
  topMatches$: Observable<Match[]>;
  allMatches$ = this.matchService.matches$;
  user$ = this.auth.user$;

  bestScore$: Observable<number>;

  initialOf = initialOf;
  hueOf = hueOf;
  ownerNameOf = ownerNameOf;
  ownerPossessive = ownerPossessive;

  showWelcome = localStorage.getItem('ps-welcome-dismissed') !== '1';
  currentUserId = '';

  dismissWelcome(): void {
    this.showWelcome = false;
    localStorage.setItem('ps-welcome-dismissed', '1');
  }

  otherPersonaOf(m: Match): Persona | null {
    const a = this.personaFrom(m, 'a');
    const b = this.personaFrom(m, 'b');
    if (!a || !b) return null;
    const aOwner = typeof a.userId === 'string' ? a.userId : a.userId?._id;
    return aOwner === this.currentUserId ? b : a;
  }

  myPersonaOf(m: Match): Persona | null {
    const a = this.personaFrom(m, 'a');
    const b = this.personaFrom(m, 'b');
    if (!a || !b) return null;
    const aOwner = typeof a.userId === 'string' ? a.userId : a.userId?._id;
    return aOwner === this.currentUserId ? a : b;
  }

  constructor(
    private personaService: PersonaService,
    private matchService: MatchService,
    private auth: AuthService,
    private router: Router,
  ) {
    this.topMatches$ = this.matchService.matches$.pipe(
      map(list => [...list].sort((a, b) => b.score - a.score).slice(0, 6)),
    );
    this.bestScore$ = this.matchService.matches$.pipe(
      map(list => list.length ? Math.max(...list.map(m => m.score)) : 0),
    );
  }

  ngOnInit(): void {
    this.auth.user$.subscribe(u => { this.currentUserId = u?.id || ''; });
    this.personaService.load().subscribe();
    this.matchService.load().subscribe();
  }

  personaFrom(m: Match, side: 'a' | 'b'): Persona | null {
    const v = side === 'a' ? m.personaAId : m.personaBId;
    return typeof v === 'string' ? null : v;
  }

  traitsOf(p: Persona): string[] { return (p.traits || []).slice(0, 3); }
  extraTraits(p: Persona): number { return Math.max(0, (p.traits || []).length - 3); }

  sharedOf(m: Match): string[] {
    const a = this.personaFrom(m, 'a');
    const b = this.personaFrom(m, 'b');
    if (!a || !b) return [];
    const setB = new Set([...(b.traits || []), ...(b.interests || [])].map(x => x.toLowerCase()));
    return Array.from(new Set(
      [...(a.traits || []), ...(a.interests || [])].filter(x => setB.has(x.toLowerCase()))
    )).slice(0, 3);
  }

  openPersona(id: string): void { this.router.navigate(['/personas', id, 'edit']); }
  openMatches(): void { this.router.navigate(['/matches']); }
  newPersona(): void { this.router.navigate(['/personas/new']); }

  personaBest(p: Persona, matches: Match[] | null): number {
    if (!matches || !p._id) return 0;
    const related = matches.filter(m => {
      const a = this.personaFrom(m, 'a'); const b = this.personaFrom(m, 'b');
      return a?._id === p._id || b?._id === p._id;
    });
    if (!related.length) return 0;
    return Math.max(...related.map(m => m.score));
  }
}

<div class="page">
  <div *ngIf="showWelcome" class="card" style="margin-bottom:20px; padding:24px; position:relative; border-left:3px solid var(--accent)">
    <button type="button" (click)="dismissWelcome()"
            style="position:absolute; top:12px; right:12px; width:28px; height:28px; border-radius:8px; background:var(--card-2); display:grid; place-items:center; color:var(--text-dim)">
      <app-icon name="x"></app-icon>
    </button>
    <div style="font-size:11px; color:var(--accent); letter-spacing:0.1em; text-transform:uppercase; font-weight:700; margin-bottom:6px">
      New here? 30-second tour
    </div>
    <h3 style="font-family:'Fraunces', serif; font-weight:500; font-size:22px; margin-bottom:12px">
      Lumi matches the <em>sides of you</em> to the sides of other people.
    </h3>
    <ul class="muted" style="margin:0; padding-left:18px; line-height:1.7; font-size:13.5px">
      <li>You have multiple <b style="color:var(--text)">selves</b> — a career self, a weekend self, a creative self. Add them under <b style="color:var(--text)">My selves</b>.</li>
      <li>Other people's selves are ranked against yours. More shared traits and interests = higher <b style="color:var(--text)">match score</b>.</li>
      <li><b style="color:var(--text)">Connections</b> shows who matches. <b style="color:var(--text)">Network</b> is the visual map. <b style="color:var(--text)">History</b> tracks how your selves have changed.</li>
    </ul>
  </div>

  <div class="dash-hero">
    <h1>Welcome back, {{ (user$ | async)?.name || 'friend' }}</h1>
    <p>This is your home view. You have
      <b style="color:var(--text)">{{ (personas$ | async)?.length || 0 }} selves</b>
      and
      <b style="color:var(--text)">{{ (allMatches$ | async)?.length || 0 }} people</b>
      whose selves match yours.
    </p>
    <div class="hero-actions">
      <button class="btn btn-ghost" routerLink="/drift"><app-icon name="clock"></app-icon> See history</button>
      <button class="btn btn-primary" (click)="newPersona()"><app-icon name="plus"></app-icon> New self</button>
    </div>
  </div>

  <div class="stat-row" style="grid-template-columns:repeat(3, 1fr)">
    <div class="stat">
      <div class="label">Your selves</div>
      <div class="value">{{ (personas$ | async)?.length || 0 }}</div>
      <div class="delta">▲ active</div>
      <svg class="spark" width="100" height="40" viewBox="0 0 100 40">
        <path d="M0 30 Q 20 20 30 22 T 55 15 T 80 10 T 100 5" stroke="var(--accent)" stroke-width="1.5" fill="none" opacity="0.6"/>
      </svg>
    </div>
    <div class="stat">
      <div class="label">Best match</div>
      <div class="value">{{ bestScore$ | async }}%</div>
      <div class="delta">▲ strong signal</div>
    </div>
    <div class="stat">
      <div class="label">People matched</div>
      <div class="value" style="color:var(--accent)">{{ (allMatches$ | async)?.length || 0 }}</div>
      <div class="delta">▲ live</div>
    </div>
  </div>

  <div class="dash-split">
    <div>
      <div class="section-head">
        <h3>Your selves</h3>
        <button class="btn btn-ghost btn-sm" routerLink="/personas">View all <app-icon name="arrR"></app-icon></button>
      </div>
      <div class="persona-grid">
        <div *ngFor="let p of personas$ | async" class="persona-card" (click)="openPersona(p._id!)">
          <div class="ghost-ring"></div>
          <app-persona-orb [initial]="initialOf(p)" [hue]="hueOf(p)" [size]="54"></app-persona-orb>
          <h4>{{ p.name }}</h4>
          <div class="meta">Mood: {{ p.moodTag || '—' }} · Goal: {{ p.connectionGoal }}</div>
          <div class="traits">
            <span *ngFor="let t of traitsOf(p)" class="chip">{{ t }}</span>
            <span *ngIf="extraTraits(p) > 0" class="chip">+{{ extraTraits(p) }}</span>
          </div>
          <div class="score-row">
            <div class="score-n">{{ personaBest(p, (allMatches$ | async)) }}<small>% best match</small></div>
            <div class="actions">
              <button class="btn btn-sm btn-ghost" (click)="$event.stopPropagation(); openPersona(p._id!)"><app-icon name="edit"></app-icon></button>
              <button class="btn btn-sm btn-primary" (click)="$event.stopPropagation(); openMatches()">See matches</button>
            </div>
          </div>
        </div>
        <div *ngIf="(personas$ | async)?.length === 0" class="card" style="grid-column:1/-1; text-align:center; padding:40px">
          <div class="muted">No personas yet.</div>
          <button class="btn btn-primary" style="margin-top:12px" (click)="newPersona()">
            <app-icon name="plus"></app-icon> Create your first self
          </button>
        </div>
      </div>
    </div>

    <div>
      <div class="section-head">
        <h3>Top matches</h3>
        <button class="btn btn-ghost btn-sm" routerLink="/matches">All matches <app-icon name="arrR"></app-icon></button>
      </div>
      <div class="match-feed">
        <div *ngFor="let m of topMatches$ | async" class="match-row" (click)="openMatches()">
          <div class="pair">
            <app-persona-orb *ngIf="personaFrom(m,'a')"
              [initial]="initialOf(personaFrom(m,'a'))" [hue]="hueOf(personaFrom(m,'a'))" [size]="34"></app-persona-orb>
            <div *ngIf="personaFrom(m,'b')"
                 [style.background]="'linear-gradient(135deg, hsl(' + hueOf(personaFrom(m,'b')) + ' 80% 65%), hsl(' + ((hueOf(personaFrom(m,'b'))+60)%360) + ' 80% 65%))'"
                 style="width:34px; height:34px; border-radius:50%; margin-left:-10px; border:2px solid var(--card); display:grid; place-items:center; color:white; font-weight:600; font-size:12px">
              {{ initialOf(personaFrom(m,'b')) }}
            </div>
          </div>
          <div class="names">
            <b>{{ ownerPossessive(myPersonaOf(m), currentUserId) }} {{ myPersonaOf(m)?.name }}
               ↔ {{ ownerPossessive(otherPersonaOf(m), currentUserId) }} {{ otherPersonaOf(m)?.name }}</b>
            <div>Shared: {{ sharedOf(m).join(' · ') || 'no obvious overlap' }}</div>
          </div>
          <div class="score">{{ m.score }}%</div>
        </div>
        <div *ngIf="(topMatches$ | async)?.length === 0" class="card" style="text-align:center; padding:24px">
          <div class="muted">No matches yet — create more personas.</div>
        </div>
      </div>
    </div>
  </div>
</div>

// src/dashboard.jsx
const { useState: dS, useEffect: dE, useMemo: dM } = React;

function Dashboard({ personas, matches, goTo, openMatch, openPersona }) {
  const topMatches = dM(() => [...matches].sort((a,b)=>b.score-a.score).slice(0,6), [matches]);
  const avgScore = dM(() => Math.round(matches.reduce((s,m)=>s+m.score,0)/matches.length), [matches]);

  return (
    <div className="page">
      <div className="dash-hero">
        <h1>Welcome back, Krishna</h1>
        <p>You currently have <b style={{color:'var(--text)'}}>{personas.length} active sides</b> and <b style={{color:'var(--text)'}}>{matches.length} new compatibility matches</b> waiting.</p>
        <div className="hero-actions">
          <button className="btn btn-primary" onClick={()=>goTo('personas-new')}><Ic.plus/> Add a New Side</button>
        </div>
      </div>

      <div className="stat-row" style={{gridTemplateColumns: 'repeat(3, 1fr)'}}>
        <StatCard label="Sides created" value={personas.length} delta="+1 this month"/>
        <StatCard label="Top match score" value={`${Math.max(...matches.map(m=>m.score))}%`} delta="+6 vs last week"/>
        <StatCard label="Matches found" value="128" delta="+18"/>
      </div>

      <div className="dash-split">
        <div>
          <div className="section-head">
            <h3>Your Sides</h3>
            <div className="row" style={{gap:8}}>
              <span className="hint">Avg compatibility · <b style={{color:'var(--text)'}}>{avgScore}%</b></span>
              <button className="btn btn-ghost btn-sm" onClick={()=>goTo('personas')}>View all <Ic.arrR/></button>
            </div>
          </div>
          <div className="persona-grid">
            {personas.map(p => (
              <div key={p.id} className="persona-card" onClick={()=>openPersona(p.id)}>
                <div className="ghost-ring"/>
                <PersonaOrb initial={p.initial} hue={p.hue} size={54}/>
                <h4>{p.name}</h4>
                <div className="meta">Mood: {p.mood} · Goal: {p.goal}</div>
                <div className="traits">
                  {p.traits.slice(0,3).map(t => <span key={t} className="chip">{t}</span>)}
                  {p.traits.length>3 && <span className="chip">+{p.traits.length-3}</span>}
                </div>
                <div className="score-row">
                  <div className="score-n">{p.scoreAvg}<small>% avg match</small></div>
                  <div className="actions">
                    <button className="btn btn-sm btn-ghost" onClick={(e)=>{e.stopPropagation(); openPersona(p.id);}}>Edit</button>
                    <button className="btn btn-sm btn-primary" onClick={(e)=>{e.stopPropagation(); goTo('matches');}}>Match</button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        <div>
          <div className="section-head">
            <h3>Top matches</h3>
            <button className="btn btn-ghost btn-sm" onClick={()=>goTo('matches')}>All matches <Ic.arrR/></button>
          </div>
          <div className="match-feed">
            {topMatches.map(m => {
              const pa = window.findPersona(m.a), pb = window.findOther(m.b);
              return (
                <div key={m.id} className="match-row" onClick={()=>openMatch(m.id)}>
                  <div className="pair">
                    <PersonaOrb initial={pa.initial} hue={pa.hue} size={34}/>
                    <div style={{width:34, height:34, borderRadius:'50%', marginLeft:-10, border:'2px solid var(--card)', background:`linear-gradient(135deg, hsl(${pb.hue} 80% 65%), hsl(${(pb.hue+60)%360} 80% 65%))`, display:'grid', placeItems:'center', color:'white', fontWeight:600, fontSize:12}}>{pb.initial}</div>
                  </div>
                  <div className="names">
                    <b>{pa.name} ↔ {pb.name}</b>
                    <div>Shared: {m.shared.join(' · ')}</div>
                  </div>
                  <div className="score">{m.score}%</div>
                </div>
              );
            })}
          </div>

          <div className="section-head" style={{marginTop:24}}>
            <h3>Connections</h3>
            <span className="hint">Visual</span>
          </div>
          <div className="card" style={{padding:16}}>
            <MiniGraph personas={personas}/>
          </div>
        </div>
      </div>
    </div>
  );
}

function StatCard({ label, value, delta, accent }) {
  return (
    <div className="stat">
      <div className="label">{label}</div>
      <div className="value" style={{color: accent ? 'var(--accent)' : undefined}}>{value}</div>
      <div className="delta">▲ {delta}</div>
      <svg className="spark" width="100" height="40" viewBox="0 0 100 40">
        <path d="M0 30 Q 20 20 30 22 T 55 15 T 80 10 T 100 5" stroke="var(--accent)" strokeWidth="1.5" fill="none" opacity="0.6"/>
      </svg>
    </div>
  );
}

function MiniGraph({ personas }) {
  // simple decorative graph — nodes on a circle + pulsing edges
  const N = personas.length;
  const R = 70, cx = 130, cy = 90;
  const pts = personas.map((p,i) => {
    const a = (i/N) * Math.PI * 2 - Math.PI/2;
    return { ...p, x: cx + R*Math.cos(a), y: cy + R*Math.sin(a) };
  });
  return (
    <svg width="100%" height="180" viewBox="0 0 260 180">
      {pts.map((a,i) => pts.slice(i+1).map((b,j) => (
        <line key={`${i}-${j}`} x1={a.x} y1={a.y} x2={b.x} y2={b.y}
          stroke="var(--accent)" strokeOpacity="0.25" strokeWidth="1">
          <animate attributeName="stroke-opacity" values="0.1;0.5;0.1" dur={`${3+i+j}s`} repeatCount="indefinite"/>
        </line>
      )))}
      {pts.map((p,i) => (
        <g key={i}>
          <circle cx={p.x} cy={p.y} r="14" fill={`hsl(${p.hue} 80% 65%)`} opacity="0.2"/>
          <circle cx={p.x} cy={p.y} r="7" fill={`hsl(${p.hue} 80% 65%)`}/>
          <text x={p.x} y={p.y+22} textAnchor="middle" fontSize="9" fill="var(--text-dim)" fontFamily="JetBrains Mono, monospace">{p.initial}</text>
        </g>
      ))}
    </svg>
  );
}

Object.assign(window, { Dashboard });
